# version: "3.8"

# x-uffizzi:
#   ingress:
#     service: tyk-dashboard
#     port: 3000

# services:

#   tyk-dashboard:
#     image: tykio/tyk-dashboard
#     volumes:
#     - ./dashboard-config:/opt/tyk-dashboard/
#     environment:
#     - TYK_DB_LISTENPORT=3000
#     - TYK_DB_TYKAPI_HOST=localhost
#     - TYK_DB_TYKAPI_PORT=8080
#     - TYK_DB_TYKAPI_SECRET=352d20ee67be67f6340b4c0605b044b7
#     - TYK_DB_MONGOURL=mongodb://admin:password@localhost:27017/tyk_analytics
#     - TYK_DB_MONGOUSESSL=false
#     - TYK_DB_MONGOSSLINSECURESKIPVERIFY=false
#     - TYK_DB_MONGOBATCHSIZE=2000
    
    
#   tyk:
#     image: "${TYK_IMAGE}"
#     ports:
#       - '8080:8080'
#     volumes:
#       - ./apps:/opt/tyk-gateway/apps
#       - ./middleware:/opt/tyk-gateway/middleware
#       - ./certs:/opt/tyk-gateway/certs
#     deploy:
#       resources:
#         limits:
#           memory: 2000M

#   redis:
#     image: redis
  
#   mongo:
#     image: mongo:latest
#     environment:
#       - MONGO_INITDB_ROOT_USERNAME=admin
#       - MONGO_INITDB_ROOT_PASSWORD=password
#     deploy:
#       resources:
#         limits:
#           memory: 2000M
#     volumes:
#       - mongodata:/data/db    
  
# volumes:
#     mongodata:    


version: '3.9'

x-uffizzi:
  ingress:
    service: tyk-dashboard
    port: 3000

services:
  
  tyk-dashboard:
    image: tykio/tyk-dashboard:v4.3
    environment:
      - TYK_DB_STORAGE_MAIN_TYPE=postgres
      - TYK_DB_STORAGE_MAIN_CONNECTIONSTRING=user=postgres password=password database='tyk_analytics' host=localhost port=5432
      - TYK_DB_LISTENPORT=3000
      - TYK_DB_ADMINSECRET=12345
      - TYK_DB_TYKAPI_HOST=http://localhost
      - TYK_DB_TYKAPI_PORT=8080
      - TYK_DB_TYKAPI_SECRET=352d20ee67be67f6340b4c0605b044b7
      - TYK_DB_NODESECRET=352d20ee67be67f6340b4c0605b044b7
      - TYK_DB_REDISHOST=localhost:6379
      - TYK_DB_REDISPASSWORD=
      - TYK_DB_ENABLECLUSTER=false
      - TYK_DB_REDISDATABASE=0
      - TYK_DB_ENABLEHASHEDKEYSLISTING=true
      - TYK_DB_LICENSEKEY=eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJhbGxvd2VkX25vZGVzIjoiMThmYzU4YzYtMjcwNC00ZGI5LTY5MTctZmIzZTc0ZTc2ZWE1LDBhY2E3ZTEyLTlhMGEtNGJjMC02M2M5LWJmYjNiMjFkMzcyOCxhZTZlYzVjYy00YjMwLTQ5NmYtNGRmMS1jMGM4ZTY1MGQ3YTEsYmIyN2UzZDAtOTVmMS00YzljLTdmNGQtMWJhZTdmZTcyNzM1LDg4MDdkMjllLTAxYjItNDUyZC02ZmVkLTk3M2EyZDg3OGQ2NCIsImV4cCI6MTY3NjM4OTg2OCwiaWF0IjoxNjc1MTgwMjY4LCJvd25lciI6IjYzZDkzOGVjZTMzZmRjMDAwMTYzMDVlNiIsInNjb3BlIjoidHJhY2sscmJhYyxtdWx0aV90ZWFtLHVkZyxncmFwaCxmZWRlcmF0aW9uIiwidiI6IjIifQ.u-wxaBARnJjvhU2eeXEc5fy00a1pvqc6M2Bg_gO4NcrkfNp8IzH5IsJ52cdhGayn6irHeZ_Nu1UIa-K1TVLxc34veeeaZuhukNibHX8vVfvKyOPE-03EXoVi1QB_GSVX7HXIaucHaqeP2db-ZiL4J0GqB1uhceY52FZWEhUBawi6dadn-IYIgenhMlVeLJT8NyyiKFdKdZKu_GWO3-0KQSaZTGp3nU_08GDFMQM9egLWSo5Im7wSkqfsRTJP8zANr5988tNmCcP-EzM_TIynQLFt6y5fsGYlSAnl_mAzDMcyUn4Jh-de7gfefrn2PLsqekncgr7UBihO_i0cxH6H-w
    ports:
      - "3000:3000"
    deploy:
      resources:
        limits:
          memory: 4000M  

  tyk-gateway:
    image: "${TYK_IMAGE}"
    ports:
      - "8080:8080"
    environment:
      - TYK_GW_LISTENPORT=8080
      - TYK_GW_SECRET=352d20ee67be67f6340b4c0605b044b7
      - TYK_GW_NODESECRET=352d20ee67be67f6340b4c0605b044b7  
    # volumes:
    #   - ./apps:/opt/tyk-gateway/apps
    #   - ./middleware:/opt/tyk-gateway/middleware
    #   - ./certs:/opt/tyk-gateway/certs
    deploy:
      resources:
        limits:
          memory: 2000M  

  tyk-redis:
    image: redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

  tyk-postgres:
    image: postgres:latest
    container_name: tyk-postgres
    environment:
      - POSTGRES_DB=tyk_analytics
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql
  
volumes:
  redis-data:
  db-data:    