version: "3.8"

x-uffizzi:
  ingress:
    service: tyk-dashboard
    port: 3000

services:

  tyk-dashboard:
    image: tykio/tyk-dashboard
    environment:
    - TYK_DB_LISTENPORT=3000
    - TYK_DB_TYKAPI_HOST=localhost
    - TYK_DB_TYKAPI_PORT=8080
    - TYK_DB_TYKAPI_SECRET=352d20ee67be67f6340b4c0605b044b7
    volumes:
      - ./dashboard-config:/opt/tyk-dashboard
    entrypoint: /bin/sh
    command: 
    - "-c"
    - "/opt/tyk-dashboard/tyk-analytics --conf=/opt/tyk-dashboard/tyk_analytics.conf"  
    

  tyk:
    image: "${TYK_IMAGE}"
    ports:
      - '8080:8080'
    volumes:
      - ./apps:/opt/tyk-gateway/apps
      - ./middleware:/opt/tyk-gateway/middleware
      - ./certs:/opt/tyk-gateway/certs
    deploy:
      resources:
        limits:
          memory: 2000M

  redis:
    image: redis
  
  sql-server-db:
    container_name: sql-server-db
    image: microsoft/mssql-server-linux:2017-latest
    ports:
      - "1433:1433"
  
volumes:
    mongodata:    
    