version: "3.8"

x-uffizzi:
  ingress:
    service: tyk-dashboard
    port: 3000

services:

  tyk-dashboard:
    image: tykio/tyk-dashboard
    environment:
    - TYK_DB_LISTENPORT=3000
    - TYK_DB_TYKAPI_HOST=localhost
    - TYK_DB_TYKAPI_PORT=8080
    - TYK_DB_TYKAPI_SECRET=352d20ee67be67f6340b4c0605b044b7
    - TYK_DB_MONGOURL=mongodb://mongo:27017/tyk
    - TYK_DB_MONGOUSESSL=true
    

  tyk:
    image: "${TYK_IMAGE}"
    volumes:
      # - ./tyk.conf.example:/opt/tyk-gateway/tyk.conf
      - ./apps:/opt/tyk-gateway/apps
      - ./middleware:/opt/tyk-gateway/middleware
      - ./certs:/opt/tyk-gateway/certs
    deploy:
      resources:
        limits:
          memory: 2000M

  redis:
    image: redis
  
  mongo:
    image: mongo:latest
    ports:
      - '27017:27017'
    deploy:
      resources:
        limits:
          memory: 4000M
    volumes:
      - mongodata:/data/db    
  
volumes:
    mongodata:    
    